trigger:
  branches:
    include:
    - master
    - develop

pr:
  branches:
    include:
    - feature/*
    - release/*
    - hotfix/*
    - pull-request/*

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: Release

stages:
- stage: 'Build'
  displayName: 'Build'
  dependsOn: ['Setup']
  jobs:
  - job: 'Build'
    displayName: 'Build, Test & Release'
    steps:
    - template: Build/build.yml