trigger:
  branches:
    include:
    - master
    - develop
    - release/*

pr:
  branches:
    include:
    - feature/*
    - release/*
    - hotfix/*
    - pull-request/*

pool:
  vmImage: 'windows-latest'

variables:
  GitVersion.SemVer: ''
  BuildConfiguration: Release

stages:
- stage: 'Setup'
  displayName: 'Setup build'
  jobs:
  - job: 'Version'
    displayName: 'Version Build'
    steps:
    - task: UseGitVersion@5
      displayName: gitversion
      inputs:
        versionSpec: '5.x'
        updateAssemblyInfo: false

- stage: 'Build'
  displayName: 'Build'
  dependsOn: ['Setup']
  jobs:
  - job: 'Build'
    displayName: 'Build, Test & Release'
    steps:
    - template: Build/build.yml