trigger:
  branches:
    include:
    - master
    - develop

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: Release

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job: 'Build'
    displayName: 'Build, Test & Release'
    steps:
    - template: Build/build.yml